"""Singapore postal districts D01-D28 with their common area names."""

DISTRICTS = [
    ("D01", "Boat Quay / Raffles Place / Marina"),
    ("D02", "Chinatown / Tanjong Pagar"),
    ("D03", "Alexandra / Commonwealth / Queenstown"),
    ("D04", "Harbourfront / Telok Blangah"),
    ("D05", "Buona Vista / West Coast / Clementi"),
    ("D06", "City Hall / Clarke Quay"),
    ("D07", "Beach Road / Bugis / Rochor"),
    ("D08", "Farrer Park / Little India"),
    ("D09", "Orchard / River Valley"),
    ("D10", "Tanglin / Holland / Bukit Timah"),
    ("D11", "Newton / Novena"),
    ("D12", "Balestier / Toa Payoh"),
    ("D13", "Macpherson / Potong Pasir"),
    ("D14", "Eunos / Geylang / Paya Lebar"),
    ("D15", "East Coast / Marine Parade / Katong"),
    ("D16", "Bedok / Upper East Coast"),
    ("D17", "Changi / Loyang"),
    ("D18", "Pasir Ris / Tampines"),
    ("D19", "Hougang / Punggol / Sengkang"),
    ("D20", "Ang Mo Kio / Bishan / Thomson"),
    ("D21", "Clementi Park / Upper Bukit Timah"),
    ("D22", "Boon Lay / Jurong / Tuas"),
    ("D23", "Bukit Batok / Bukit Panjang / CCK"),
    ("D24", "Kranji / Lim Chu Kang / Tengah"),
    ("D25", "Admiralty / Woodlands"),
    ("D26", "Mandai / Upper Thomson"),
    ("D27", "Sembawang / Yishun"),
    ("D28", "Seletar / Yio Chu Kang"),
]
